import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NextAuthProvider from "@/providers/NextAuthProvider";
import { getServerSession } from "next-auth";
import { authOptions } from "./api/auth/[...nextauth]/route";
import Navbar from "@/components/Navbar";
import Providers from "./provider";
import ThemeButton from "@/components/ThemeButton";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const nextAuthSession = await getServerSession(authOptions);

  return (
    <html lang="en" className="">
      <body className={inter.className}>
        {" "}
        <NextAuthProvider session={nextAuthSession}>
          <Providers>
            <div className="w-screen top-0 sticky drop-shadow-lg bg-white z-30">
              <Navbar />
            </div>
            {children}
            <ThemeButton />
            </Providers>
        </NextAuthProvider>
      </body>
    </html>
  );
}
